UPD v2.0.2 (see changelog)

diff --git a/.github/workflows/npm_publish_on_pr_merge_to_master.yml b/.github/workflows/npm_publish_on_pr_merge_to_master.yml
--- a/.github/workflows/npm_publish_on_pr_merge_to_master.yml
+++ b/.github/workflows/npm_publish_on_pr_merge_to_master.yml
@@ -38,7 +38,7 @@ jobs:
         if: ${{ env.MASTER_IS_MERGED }} == 'true'
         run: |
           if [ $(git tag -l "v${{ steps.get_version.outputs.version }}") ]; then
-            echo "::error::Tag v${{ steps.get_version.outputs.version }} already exists."
+            echo "::error::Tag v${{ steps.get_version.outputs.version }} already exists." && exit 1
           fi
 
   tag:
@@ -85,11 +85,17 @@ jobs:
 
       - name: "Create GitHub Release"
         if: ${{ env.MASTER_IS_MERGED }} == 'true'
+        uses: actions/create-release@latest
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PROJECT_VERSION: ${{needs.tag.outputs.PROJECT_VERSION}}
-        run: |
-          gh release create "v${{ env.PROJECT_VERSION }}" "./dist/*" --title "Release v${{ env.PROJECT_VERSION }}" --notes "Release notes for v${{ env.PROJECT_VERSION }}"
+        with:
+          tag_name: v${{ env.PROJECT_VERSION }}
+          release_name: Release v${{ env.PROJECT_VERSION }}
+          body: |
+            Release notes for v${{ env.PROJECT_VERSION }}
+          draft: false
+          prerelease: false
 
   publish:
     runs-on: ubuntu-latest
