UPD v2.0.2 (see changelog)

diff --git a/.github/workflows/validate_pr_to_master.yml b/.github/workflows/validate_pr_to_master.yml
--- a/.github/workflows/validate_pr_to_master.yml
+++ b/.github/workflows/validate_pr_to_master.yml
@@ -46,7 +46,7 @@ jobs:
 
       - name: "Check if Tag Exists"
         run: |
-          echo "::error::Tag v${{ steps.get_version.outputs.version }} already exists."
+          echo "::error::Tag v${{ steps.get_version.outputs.version }} already exists." && exit 1
           if [ $(git tag -l "v${{ steps.get_version.outputs.version }}") ]; then
-            echo "::error::Tag v${{ steps.get_version.outputs.version }} already exists."
+            echo "::error::Tag v${{ steps.get_version.outputs.version }} already exists." && exit 1
           fi
